from __future__ import annotations
import json, math, time
from pathlib import Path
import numpy as np
import r35_base as r
import r37_base as r37
import r52_base as r52

NOISE=0.30
WIDTH=32
EXPAND=8
MAX_K=8
# Exact BSC log-likelihood coefficient for normalized +/-1 codewords.
BSC_KAPPA=(r.PHYS/2.0)*math.log((1.0-NOISE)/NOISE)


def load_assets(root: Path):
    model,alpha,perms=r37.load_base(root)
    z=np.load(root/'r52_ecc_model.npz',allow_pickle=False)
    cb=np.asarray(z['codebook'],np.float32)
    cb=r.norm(cb)
    return model,alpha,perms,cb


def build_episode(cn:str, seed:int, perms, cb):
    st=r52.make_structure(*r.CONDS[cn],seed,perms)
    ep=r52.episode_from_structure(st,'optimized_linear',cb*np.sqrt(r.PHYS),cb*np.sqrt(r.PHYS))
    # true code IDs for current address at every query step, for decoder diagnostics only
    ep['true_code_ids']=np.asarray(st['code_ids'][st['path'][:-1]],dtype=np.int64)
    return ep


def precompute_decoder(ep, cb, max_k=MAX_K):
    # q sources: initial query at row 0, then every noisy object at rows 1..N
    Q=np.vstack([ep['q'][None,:],ep['obj']]).astype(np.float32)
    sim=Q@cb.T
    logits=BSC_KAPPA*sim
    # stable log-softmax
    m=logits.max(axis=1,keepdims=True)
    lse=m+np.log(np.exp(logits-m).sum(axis=1,keepdims=True)+1e-30)
    logp=logits-lse
    k=min(max_k,cb.shape[0])
    top=np.argpartition(logp,-k,axis=1)[:,-k:]
    vals=np.take_along_axis(logp,top,axis=1)
    ord2=np.argsort(vals,axis=1)[:,::-1]
    top=np.take_along_axis(top,ord2,axis=1)
    vals=np.take_along_axis(vals,ord2,axis=1)
    return top.astype(np.int32), vals.astype(np.float32)


def precompute_edge_orders(ep, cb, expand=EXPAND):
    # Candidate-generation only: clean decoded address -> top memory edges for each relation.
    sim=ep['sub']@cb.T  # edges x codewords
    out={}
    n=len(ep['rel'])
    for rr in range(r.R):
        L=10.0*sim + (3.0*(ep['rel']==rr)+2.0*ep['ts'])[:,None]
        k=min(expand,n)
        idx=np.argpartition(L,-k,axis=0)[-k:,:]  # k x codewords
        vals=np.take_along_axis(L,idx,axis=0)
        o=np.argsort(vals,axis=0)[::-1]
        idx=np.take_along_axis(idx,o,axis=0).T  # codewords x k
        out[rr]=idx.astype(np.int32)
    return out


def multi_hyp_decode_beam(ep, perms, base_model, alpha, cb, k_decode:int, beta:float):
    """Discrete ECC address hypotheses expand candidate support; R35 scorer remains frozen.

    Each beam hypothesis carries the original noisy pointer source index, not a soft address vector.
    Decoder codeword hypotheses are discrete and discarded only after a concrete memory edge is chosen.
    """
    sids,latest,fut_tab,fm_tab=r.prep(ep)
    dtop,dlp=precompute_decoder(ep,cb,MAX_K)
    eorders=precompute_edge_orders(ep,cb,EXPAND)
    # score, qsrc (-1=query else edge index), state, prefix_ok, used, clp, cm, cf
    hyps=[(0.0,-1,int(ep['start']),True,frozenset(),0.0,0.0,0.0)]
    surv=[]; evals=0; decode_true=[]
    for j,rel0 in enumerate(ep['prog']):
        rel=int(rel0); cand=[]
        # diagnostic: true code in top-k for the true pointer source only
        true_src=0 if j==0 else int(ep['idx'][j-1])+1
        decode_true.append(float(int(ep['true_code_ids'][j]) in set(map(int,dtop[true_src,:k_decode]))))
        for score,qsrc,st,pok,used,clp,cm,cf in hyps:
            src=0 if qsrc<0 else qsrc+1
            q=ep['q'] if qsrc<0 else ep['obj'][qsrc]
            # Frozen R35 features are computed on the original noisy q to avoid distribution shift.
            raw_logits=10*(ep['sub']@q)+3*(ep['rel']==rel)+2*ep['ts']
            p,raw_order,margin,ent=r.softstats(raw_logits)
            # Union discrete candidate edges generated by k decoded codewords.
            edge_best={}
            for kk in range(k_decode):
                cid=int(dtop[src,kk]); prior=beta*float(dlp[src,kk])
                for ix0 in eorders[rel][cid]:
                    ix=int(ix0); evals+=1
                    f=r.feat(ep,j,q,ix,p,margin,ent,sids,latest,fut_tab,fm_tab,used,clp,cm,cf)
                    ns=score+r.verifier_score(base_model,f)+alpha*f[3]+prior
                    old=edge_best.get(ix)
                    if old is None or ns>old[0]: edge_best[ix]=(ns,f,cid)
            for ix,(ns,f,cid) in edge_best.items():
                key=(int(sids[ix]),int(ep['rel'][ix]))
                cand.append((ns,ix,int(perms[int(ep['op'][ix]),st]),pok and ix==int(ep['idx'][j]),used|{key},clp+f[3],cm+margin,cf+f[8]))
        cand.sort(key=lambda x:x[0],reverse=True)
        hyps=[(sc,ix,st,pok,used,clp,cm,cf) for sc,ix,st,pok,used,clp,cm,cf in cand[:WIDTH]]
        surv.append(any(h[3] for h in hyps))
    best=hyps[0]
    return {
        'state':int(best[2]),'path_survival':float(np.mean(surv)),'final_true_path_in_beam':float(surv[-1]),
        'selected_true_path':float(best[3]),'candidate_evals':int(evals),
        'decoder_true_in_topk':float(np.mean(decode_true)),'decoder_final_true_in_topk':float(decode_true[-1])
    }


def baseline_r52(ep,perms,base_model,alpha):
    z=r37.baseline_fixed(ep,r.prep(ep),perms,base_model,alpha,WIDTH,EXPAND)
    z['answer']=float(z['state']==int(ep['target']))
    return z


def evaluate(cn,seeds,n,assets,cb,k,beta):
    base,alpha,perms,_cb=assets
    rows={m:[] for m in ['r52_ecc_r35','r53_topk_decoder','ablation_hard_decode']}
    semantic_mismatch=0
    for sd in seeds:
        for i in range(n):
            ep=build_episode(cn,sd*100000+i,perms,cb)
            semantic_mismatch += int(not r52.semantic_validate(ep,perms))
            z=baseline_r52(ep,perms,base,alpha); z['seed']=sd; rows['r52_ecc_r35'].append(z)
            z=multi_hyp_decode_beam(ep,perms,base,alpha,cb,k,beta); z['answer']=float(z['state']==int(ep['target']));z['seed']=sd;rows['r53_topk_decoder'].append(z)
            z=multi_hyp_decode_beam(ep,perms,base,alpha,cb,1,beta); z['answer']=float(z['state']==int(ep['target']));z['seed']=sd;rows['ablation_hard_decode'].append(z)
    return {m:summarize(v) for m,v in rows.items()},semantic_mismatch


def summarize(rows):
    keys=['answer','path_survival','final_true_path_in_beam','selected_true_path','candidate_evals']
    extra=['decoder_true_in_topk','decoder_final_true_in_topk']
    out={'n_episodes':len(rows)}
    for key in keys+extra:
        vals=[float(x[key]) for x in rows if key in x]
        if vals:
            a=np.asarray(vals,float);out[key]={'mean':float(a.mean()),'std':float(a.std()),'values':a.tolist()}
    out['seeds']=[]
    for sd in sorted(set(int(x['seed']) for x in rows)):
        rr=[x for x in rows if int(x['seed'])==sd]; z={'seed':sd,'n':len(rr)}
        for key in keys+extra:
            vals=[float(x[key]) for x in rr if key in x]
            if vals:
                a=np.asarray(vals,float);z[key]={'mean':float(a.mean()),'std':float(a.std())}
        out['seeds'].append(z)
    return out


def calibrate(root:Path,assets,cb,seeds=(5321,5322),n=1):
    # Separate calibration; select a single k and beta before held-out.
    grid=[(2,.10),(2,.25),(4,.10),(4,.25),(8,.10),(8,.25)]
    vals=[]
    base,alpha,perms,_cb=assets
    episodes=[]
    for cn in ['id8','ood64','ood128']:
        for sd in seeds:
            for i in range(n): episodes.append((cn,sd,build_episode(cn,sd*100000+i,perms,cb)))
    for k,beta in grid:
        by={'id8':[],'ood64':[],'ood128':[]}
        for cn,sd,ep in episodes:
            z=multi_hyp_decode_beam(ep,perms,base,alpha,cb,k,beta);z['answer']=float(z['state']==int(ep['target']));z['seed']=sd;by[cn].append(z)
        sm={cn:summarize(rr) for cn,rr in by.items()}
        # protect 8-hop; emphasize long horizon, plus final path survival
        obj=2*sm['id8']['answer']['mean']+sm['ood64']['answer']['mean']+2*sm['ood128']['answer']['mean']+0.5*sm['ood128']['final_true_path_in_beam']['mean']
        vals.append({'k':k,'beta':beta,'objective':float(obj),'summary':sm})
    vals.sort(key=lambda x:(x['objective'],-x['k'],-x['beta']),reverse=True)
    return {'seeds':list(seeds),'n_per_condition_seed':n,'grid':grid,'selected':{'k':vals[0]['k'],'beta':vals[0]['beta']},'trials':vals}

if __name__=='__main__':
    import argparse
    ap=argparse.ArgumentParser();ap.add_argument('--root',default='.');ap.add_argument('--mode',choices=['pilot','calibrate','held'],default='pilot');ap.add_argument('--condition',default='ood64');ap.add_argument('--n',type=int,default=1);args=ap.parse_args()
    root=Path(args.root); assets=load_assets(root); cb=load_assets(root)[3]
    if args.mode=='pilot':
        t=time.time();z,sem=evaluate(args.condition,[5341],args.n,assets,cb,4,.10);print(json.dumps(z,indent=2));print('sem',sem,'sec',time.time()-t)
    elif args.mode=='calibrate':
        t=time.time();z=calibrate(root,assets,cb);print(json.dumps(z,indent=2));print('sec',time.time()-t)
    else:
        z,sem=evaluate(args.condition,[5341,5342,5343],args.n,assets,cb,4,.10);print(json.dumps({'results':z,'sem':sem},indent=2))