"""One finite public CPU continuation with real native-weight release.

Never trains/replays parent models. Pins their original immutable receipt.
Every asset is downloaded back and SHA256 checked before being reported saved.
The run-scoped prerelease remains a draft until all six endpoints complete.
"""
from __future__ import annotations
import gzip,hashlib,json,os,shutil,subprocess,sys,tarfile,tempfile,urllib.request
from pathlib import Path
import torch
import study as ex
REPO='binouv/model';BRANCH='flygraph/g8c-consolidation-20260926'
ROOT=ex.ROOT;TOP=ROOT.parents[1]
PARENT_RELEASE_ID=397157104

def gh(*args):return subprocess.check_output(['gh',*args],text=True)
def api(method,path,obj=None):
 if os.environ.get('GITHUB_REPOSITORY')!=REPO:raise ValueError('wrong repository')
 headers={'Authorization':'Bearer '+os.environ['GH_TOKEN'],'Accept':'application/vnd.github+json','Content-Type':'application/json'}
 req=urllib.request.Request('https://api.github.com/repos/'+REPO+path,data=None if obj is None else json.dumps(obj).encode(),headers=headers,method=method)
 with urllib.request.urlopen(req,timeout=90) as f:return json.load(f)
def push(files):
 head=api('GET','/git/ref/heads/'+BRANCH)['object']['sha'];tree=api('GET','/git/commits/'+head)['tree']['sha']
 entries=[{'path':str(p.relative_to(TOP)),'mode':'100644','type':'blob','content':p.read_text()} for p in files]
 tr=api('POST','/git/trees',{'base_tree':tree,'tree':entries})['sha']
 co=api('POST','/git/commits',{'tree':tr,'parents':[head],'message':'FlyGraph G8C: save completed continuation stage and actual asset receipts'})['sha']
 api('PATCH','/git/refs/heads/'+BRANCH,{'sha':co,'force':False});print('FG_PUSH',co,flush=True);return co

def main():
 torch.set_num_threads(4);torch.set_num_interop_threads(1)
 for folder in ['reports','metrics','assets','parents']: (ROOT/folder).mkdir(parents=True,exist_ok=True)
 # Immutable receipt is a committed raw file, not a claim of downloaded weights.
 raw=(ROOT/'base/PARENT_REPLAY.json').read_bytes()
 blob=hashlib.sha1(b'blob '+str(len(raw)).encode()+b'\0'+raw).hexdigest()
 assert blob=='3ae441a949907244640c8ea54ac45eaccf6b11c4'
 receipt=json.loads(raw);assert receipt['status']=='completed_CPU_reproduction'
 rel=api('GET',f'/releases/{PARENT_RELEASE_ID}');assert not rel['draft']
 parents={};sources=[]
 for z in receipt['runs']:
  arm,seed=z['arm'],z['seed'];name=f'{arm}_s{seed}_step1000.resume.pt';expect=z['checkpoint_manifest']['files']['resume.pt'];p=ROOT/'parents'/name
  gh('release','download',rel['tag_name'],'--repo',REPO,'--pattern',name,'--dir',str(p.parent))
  assert p.stat().st_size==expect['bytes'] and ex.sha(p)==expect['sha256']
  # Hash-verified native checkpoint generated by the user's own prior run.
  st=torch.load(p,weights_only=False,map_location='cpu')
  assert st['schema']=='G5S_v1' and st['step']==1000 and st['arm']==arm and st['seed']==seed
  parents[arm,seed]=p;sources.append({'name':name,**expect,'actual_bytes_downloaded_and_verified':True})
 ex.put(ROOT/'reports/PARENT_AUDIT.json',{'status':'completed','sources':sources,'source_receipt_blob':blob,'optimizer_rng_present':True,'parent_models_retrained':False})
 audit=ex.prepare();expected=json.loads((ROOT/'configs/fresh_expected.json').read_text())
 assert audit['fresh_sha256']==expected
 tag='flygraph-g8c-consolidation-'+os.environ['GITHUB_RUN_ID'];assets=ROOT/'assets';receipts=[]
 gh('release','create',tag,'--repo',REPO,'--target',os.environ['GITHUB_SHA'],'--title','FlyGraph G8C: six continued research checkpoints','--notes','DRAFT: incomplete until all6fixed continuations finish;469648params,not300M.','--draft','--prerelease')
 def upload(paths):
  gh('release','upload',tag,'--repo',REPO,*map(str,paths));out=[]
  with tempfile.TemporaryDirectory() as td:
   for p in paths:
    gh('release','download',tag,'--repo',REPO,'--pattern',p.name,'--dir',td);q=Path(td)/p.name
    assert ex.sha(p)==ex.sha(q) and p.stat().st_size==q.stat().st_size
    out.append({'name':p.name,'bytes':p.stat().st_size,'sha256':ex.sha(p),'remote_redownload_sha256_verified':True})
  receipts.extend(out);return out
 def publish(cp,arm,seed,step,result):
  stem=f'{arm}_s{seed}'
  if result is None:
   path=assets/f'{stem}_stage2_{step:04d}.resume.pt';shutil.copy2(cp/'resume.pt',path);up=upload([path])
   ex.put(ROOT/'reports/PROGRESS.json',{'status':'checkpoint_completed_not_whole_grid','arm':arm,'seed':seed,'stage2_step':step,'release_tag':tag,'asset':up[0]})
   push([ROOT/'reports/PROGRESS.json',ROOT/'reports/NEXT_STATE.json']);return
  paths=[]
  for old,new in [('model.safetensors',stem+'.safetensors'),('config.json',stem+'.config.json')]:
   p=assets/new;shutil.copy2(cp/old,p);paths.append(p)
  raw=assets/(stem+'.RAW.json.gz');raw.write_bytes(gzip.compress(json.dumps(result).encode(),mtime=0));paths.append(raw);up=upload(paths)
  short={k:v for k,v in result.items() if k not in ['tests','before']}
  for name in ['tests','before']:short[name]={s:{k:v for k,v in t.items() if k!='rows'} for s,t in result[name].items()}
  short['release_assets']=up;out=ROOT/'reports'/f'{stem}.COMPLETED.json';ex.put(out,short);push([out])
 push([p for folder in ['src','tests','configs','base'] for p in sorted((ROOT/folder).rglob('*')) if p.is_file() and p.suffix in ('.py','.json')]+[ROOT/'README.md',ROOT/'reports/PARENT_AUDIT.json',ROOT/'reports/DATA_AUDIT.json'])
 for seed in ex.SEEDS:
  for arm in ex.ARMS:ex.train(arm,seed,parents[arm,seed],publish)
 final=ex.aggregate();release=ROOT/'reports/RELEASE_RECEIPT.json'
 # source/data/raw/optimizer are in real assets; no user-home files included.
 archive=assets/'SOURCE_DATA_RESULTS.tar.gz'
 with tarfile.open(archive,'w:gz') as tf:
  for p in sorted(ROOT.rglob('*')):
   if not p.is_file() or any(x in p.relative_to(ROOT).parts for x in ['assets','parents','checkpoints','__pycache__']):continue
   tf.add(p,arcname=str(p.relative_to(ROOT)))
 upload([archive])
 ex.put(release,{'status':'six_continuations_completed','tag':tag,'source_commit':os.environ['GITHUB_SHA'],'workflow_run':os.environ['GITHUB_RUN_ID'],'assets':receipts,'all_assets_redownload_verified':True,'native_optimizer_rng_present':True,'parent_models_retrained':False,'new_independent_initialization_seeds':0,'ancestral_seeds':list(ex.SEEDS)})
 manifest=assets/'MANIFEST.json';shutil.copy2(release,manifest);upload([manifest])
 gh('release','edit',tag,'--repo',REPO,'--draft=false','--prerelease','--notes','All6G8C continuations completed: trace/final-only G5S CPU parents,3ancestral seeds,1000additional updates each. Original parent weights+optimizer/RNG restored. Actual safetensors and native optimizer/RNG assets,source,data and all before/after raw predictions. Every uploaded asset redownloaded and SHA256 verified.469648parameter English synthetic probes,not300-800M orQwen parity. See FINAL.json for negative/positive criterion verdict.')
 ns=json.loads((ROOT/'reports/NEXT_STATE.json').read_text());ns['release_tag']=tag;ns['weight_publication']='actual uploaded/redownload-verified bytes';ex.put(ROOT/'reports/NEXT_STATE.json',ns)
 push([ROOT/'metrics/FINAL.json',ROOT/'metrics/FINAL.csv',ROOT/'reports/REPORT.md',ROOT/'reports/NEXT_STATE.json',release])
 print('FG_FINAL',json.dumps({'tag':tag,'verdict':final['verdict'],'gains_pp':final['gains_pp'],'results':final['results']}),flush=True)
if __name__=='__main__':main()
